import { c as create_ssr_component, v as validate_component } from "../../../chunks/ssr.js";
import { C as Container } from "../../../chunks/Container.js";
const css = {
  code: "h1.svelte-12qz3zu{font-family:var(--font-bold);font-size:2.2rem;margin-bottom:var(--space-md);color:var(--color-text)}p.svelte-12qz3zu{font-size:1.1rem;margin-bottom:var(--space-lg);color:var(--color-text);line-height:1.6}ul.svelte-12qz3zu{list-style:disc inside;color:var(--color-text);font-size:1rem;padding-left:var(--space-md)}li.svelte-12qz3zu{margin-bottom:var(--space-sm)}",
  map: '{"version":3,"file":"+page.svelte","sources":["+page.svelte"],"sourcesContent":["<script lang=\\"ts\\">\\n  import Container from \\"$lib/components/Container.svelte\\";\\n<\/script>\\n\\n<svelte:head>\\n  <title>Sobre el Servicio — Menucom</title>\\n  <meta name=\\"description\\" content=\\"Conocé cómo Menucom ayuda a restaurantes y comercios gastronómicos a gestionar menús y pedidos online.\\" />\\n</svelte:head>\\n\\n<Container>\\n  <h1>Sobre el Servicio</h1>\\n  <p>\\n    Menucom es una plataforma digital diseñada para facilitar la gestión de menús y pedidos en restaurantes y comercios gastronómicos. Nuestro objetivo es brindar una experiencia ágil, moderna y eficiente tanto para los comercios como para sus clientes.\\n  </p>\\n  <ul>\\n    <li>Gestión de menús digitalizados</li>\\n    <li>Pedidos en tiempo real</li>\\n    <li>Soporte técnico dedicado</li>\\n    <li>Actualizaciones constantes</li>\\n  </ul>\\n</Container>\\n\\n<style>\\n  h1 {\\n    font-family: var(--font-bold);\\n    font-size: 2.2rem;\\n    margin-bottom: var(--space-md);\\n    color: var(--color-text);\\n  }\\n\\n  p {\\n    font-size: 1.1rem;\\n    margin-bottom: var(--space-lg);\\n    color: var(--color-text);\\n    line-height: 1.6;\\n  }\\n\\n  ul {\\n    list-style: disc inside;\\n    color: var(--color-text);\\n    font-size: 1rem;\\n    padding-left: var(--space-md);\\n  }\\n\\n  li {\\n    margin-bottom: var(--space-sm);\\n  }\\n</style>\\n"],"names":[],"mappings":"AAuBE,iBAAG,CACD,WAAW,CAAE,IAAI,WAAW,CAAC,CAC7B,SAAS,CAAE,MAAM,CACjB,aAAa,CAAE,IAAI,UAAU,CAAC,CAC9B,KAAK,CAAE,IAAI,YAAY,CACzB,CAEA,gBAAE,CACA,SAAS,CAAE,MAAM,CACjB,aAAa,CAAE,IAAI,UAAU,CAAC,CAC9B,KAAK,CAAE,IAAI,YAAY,CAAC,CACxB,WAAW,CAAE,GACf,CAEA,iBAAG,CACD,UAAU,CAAE,IAAI,CAAC,MAAM,CACvB,KAAK,CAAE,IAAI,YAAY,CAAC,CACxB,SAAS,CAAE,IAAI,CACf,YAAY,CAAE,IAAI,UAAU,CAC9B,CAEA,iBAAG,CACD,aAAa,CAAE,IAAI,UAAU,CAC/B"}'
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-vbxd8z_START -->${$$result.title = `<title>Sobre el Servicio — Menucom</title>`, ""}<meta name="description" content="Conocé cómo Menucom ayuda a restaurantes y comercios gastronómicos a gestionar menús y pedidos online."><!-- HEAD_svelte-vbxd8z_END -->`, ""} ${validate_component(Container, "Container").$$render($$result, {}, {}, {
    default: () => {
      return `<h1 class="svelte-12qz3zu" data-svelte-h="svelte-17cpk4k">Sobre el Servicio</h1> <p class="svelte-12qz3zu" data-svelte-h="svelte-jofmbz">Menucom es una plataforma digital diseñada para facilitar la gestión de menús y pedidos en restaurantes y comercios gastronómicos. Nuestro objetivo es brindar una experiencia ágil, moderna y eficiente tanto para los comercios como para sus clientes.</p> <ul class="svelte-12qz3zu" data-svelte-h="svelte-kkqf0d"><li class="svelte-12qz3zu">Gestión de menús digitalizados</li> <li class="svelte-12qz3zu">Pedidos en tiempo real</li> <li class="svelte-12qz3zu">Soporte técnico dedicado</li> <li class="svelte-12qz3zu">Actualizaciones constantes</li></ul>`;
    }
  })}`;
});
export {
  Page as default
};
