import { c as create_ssr_component, v as validate_component } from "../../../chunks/ssr.js";
import { C as Container } from "../../../chunks/Container.js";
const css = {
  code: "h1.svelte-1dkzrh2{font-family:var(--font-bold);font-size:2.2rem;margin-bottom:var(--space-md);color:var(--color-text)}p.svelte-1dkzrh2{font-size:1.1rem;margin-bottom:var(--space-lg);color:var(--color-text);line-height:1.6}ol.svelte-1dkzrh2{color:var(--color-text);font-size:1rem;padding-left:var(--space-md)}li.svelte-1dkzrh2{margin-bottom:var(--space-sm)}",
  map: '{"version":3,"file":"+page.svelte","sources":["+page.svelte"],"sourcesContent":["<script lang=\\"ts\\">\\n  import Container from \\"$lib/components/Container.svelte\\";\\n<\/script>\\n\\n<svelte:head>\\n  <title>Términos y Condiciones — Menucom</title>\\n  <meta name=\\"description\\" content=\\"Términos y condiciones de uso de la plataforma Menucom.\\" />\\n</svelte:head>\\n\\n<Container>\\n  <h1>Términos y Condiciones</h1>\\n  <p>\\n    Al utilizar Menucom, aceptas los siguientes términos y condiciones. La plataforma se reserva el derecho de modificar estos términos en cualquier momento.\\n  </p>\\n  <ol>\\n    <li>El uso de la plataforma es responsabilidad del usuario.</li>\\n    <li>Menucom no se responsabiliza por la información ingresada por los comercios.</li>\\n    <li>Los datos personales serán tratados conforme a la legislación vigente.</li>\\n    <li>El servicio puede ser suspendido o modificado sin previo aviso.</li>\\n  </ol>\\n</Container>\\n\\n<style>\\n  h1 {\\n    font-family: var(--font-bold);\\n    font-size: 2.2rem;\\n    margin-bottom: var(--space-md);\\n    color: var(--color-text);\\n  }\\n\\n  p {\\n    font-size: 1.1rem;\\n    margin-bottom: var(--space-lg);\\n    color: var(--color-text);\\n    line-height: 1.6;\\n  }\\n\\n  ol {\\n    color: var(--color-text);\\n    font-size: 1rem;\\n    padding-left: var(--space-md);\\n  }\\n\\n  li {\\n    margin-bottom: var(--space-sm);\\n  }\\n</style>\\n"],"names":[],"mappings":"AAuBE,iBAAG,CACD,WAAW,CAAE,IAAI,WAAW,CAAC,CAC7B,SAAS,CAAE,MAAM,CACjB,aAAa,CAAE,IAAI,UAAU,CAAC,CAC9B,KAAK,CAAE,IAAI,YAAY,CACzB,CAEA,gBAAE,CACA,SAAS,CAAE,MAAM,CACjB,aAAa,CAAE,IAAI,UAAU,CAAC,CAC9B,KAAK,CAAE,IAAI,YAAY,CAAC,CACxB,WAAW,CAAE,GACf,CAEA,iBAAG,CACD,KAAK,CAAE,IAAI,YAAY,CAAC,CACxB,SAAS,CAAE,IAAI,CACf,YAAY,CAAE,IAAI,UAAU,CAC9B,CAEA,iBAAG,CACD,aAAa,CAAE,IAAI,UAAU,CAC/B"}'
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-mbahjs_START -->${$$result.title = `<title>Términos y Condiciones — Menucom</title>`, ""}<meta name="description" content="Términos y condiciones de uso de la plataforma Menucom."><!-- HEAD_svelte-mbahjs_END -->`, ""} ${validate_component(Container, "Container").$$render($$result, {}, {}, {
    default: () => {
      return `<h1 class="svelte-1dkzrh2" data-svelte-h="svelte-17tbmsi">Términos y Condiciones</h1> <p class="svelte-1dkzrh2" data-svelte-h="svelte-ujgt7o">Al utilizar Menucom, aceptas los siguientes términos y condiciones. La plataforma se reserva el derecho de modificar estos términos en cualquier momento.</p> <ol class="svelte-1dkzrh2" data-svelte-h="svelte-1t9u5ob"><li class="svelte-1dkzrh2">El uso de la plataforma es responsabilidad del usuario.</li> <li class="svelte-1dkzrh2">Menucom no se responsabiliza por la información ingresada por los comercios.</li> <li class="svelte-1dkzrh2">Los datos personales serán tratados conforme a la legislación vigente.</li> <li class="svelte-1dkzrh2">El servicio puede ser suspendido o modificado sin previo aviso.</li></ol>`;
    }
  })}`;
});
export {
  Page as default
};
