import { c as create_ssr_component, v as validate_component } from "../../../chunks/ssr.js";
import { C as Container } from "../../../chunks/Container.js";
const css = {
  code: "h1.svelte-oiduv9{font-family:var(--font-bold);font-size:2.2rem;margin-bottom:var(--space-md);color:var(--color-text)}p.svelte-oiduv9{font-size:1.1rem;margin-bottom:var(--space-lg);color:var(--color-text);line-height:1.6}ul.svelte-oiduv9{list-style:disc inside;color:var(--color-text);font-size:1rem;padding-left:var(--space-md);margin-bottom:var(--space-lg)}li.svelte-oiduv9{margin-bottom:var(--space-sm)}a.svelte-oiduv9{color:var(--color-primary);text-decoration:underline}",
  map: '{"version":3,"file":"+page.svelte","sources":["+page.svelte"],"sourcesContent":["<script lang=\\"ts\\">\\n  import Container from \\"$lib/components/Container.svelte\\";\\n<\/script>\\n\\n<svelte:head>\\n  <title>Contacta al desarrollador — Menucom</title>\\n  <meta name=\\"description\\" content=\\"Contacto directo con el equipo de desarrollo de Menucom.\\" />\\n</svelte:head>\\n\\n<Container>\\n  <h1>Contacta al desarrollador</h1>\\n  <p>\\n    ¿Querés consultar algo o reportar un error? Escribíme a:\\n  </p>\\n  <ul>\\n    <li>Email: <a href=\\"mailto:alejandrofarel62@gmail.com\\">alejandrofarel62@gmail.com</a></li>\\n  </ul>\\n  <p>\\n    También puedes enviarme sugerencias o ideas para mejorar la plataforma.\\n  </p>\\n</Container>\\n\\n<style>\\n  h1 {\\n    font-family: var(--font-bold);\\n    font-size: 2.2rem;\\n    margin-bottom: var(--space-md);\\n    color: var(--color-text);\\n  }\\n\\n  p {\\n    font-size: 1.1rem;\\n    margin-bottom: var(--space-lg);\\n    color: var(--color-text);\\n    line-height: 1.6;\\n  }\\n\\n  ul {\\n    list-style: disc inside;\\n    color: var(--color-text);\\n    font-size: 1rem;\\n    padding-left: var(--space-md);\\n    margin-bottom: var(--space-lg);\\n  }\\n\\n  li {\\n    margin-bottom: var(--space-sm);\\n  }\\n\\n  a {\\n    color: var(--color-primary);\\n    text-decoration: underline;\\n  }\\n</style>\\n"],"names":[],"mappings":"AAuBE,gBAAG,CACD,WAAW,CAAE,IAAI,WAAW,CAAC,CAC7B,SAAS,CAAE,MAAM,CACjB,aAAa,CAAE,IAAI,UAAU,CAAC,CAC9B,KAAK,CAAE,IAAI,YAAY,CACzB,CAEA,eAAE,CACA,SAAS,CAAE,MAAM,CACjB,aAAa,CAAE,IAAI,UAAU,CAAC,CAC9B,KAAK,CAAE,IAAI,YAAY,CAAC,CACxB,WAAW,CAAE,GACf,CAEA,gBAAG,CACD,UAAU,CAAE,IAAI,CAAC,MAAM,CACvB,KAAK,CAAE,IAAI,YAAY,CAAC,CACxB,SAAS,CAAE,IAAI,CACf,YAAY,CAAE,IAAI,UAAU,CAAC,CAC7B,aAAa,CAAE,IAAI,UAAU,CAC/B,CAEA,gBAAG,CACD,aAAa,CAAE,IAAI,UAAU,CAC/B,CAEA,eAAE,CACA,KAAK,CAAE,IAAI,eAAe,CAAC,CAC3B,eAAe,CAAE,SACnB"}'
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-ya4gal_START -->${$$result.title = `<title>Contacta al desarrollador — Menucom</title>`, ""}<meta name="description" content="Contacto directo con el equipo de desarrollo de Menucom."><!-- HEAD_svelte-ya4gal_END -->`, ""} ${validate_component(Container, "Container").$$render($$result, {}, {}, {
    default: () => {
      return `<h1 class="svelte-oiduv9" data-svelte-h="svelte-1sm6kx6">Contacta al desarrollador</h1> <p class="svelte-oiduv9" data-svelte-h="svelte-mhfztk">¿Querés consultar algo o reportar un error? Escribíme a:</p> <ul class="svelte-oiduv9" data-svelte-h="svelte-1scxly8"><li class="svelte-oiduv9">Email: <a href="mailto:alejandrofarel62@gmail.com" class="svelte-oiduv9">alejandrofarel62@gmail.com</a></li></ul> <p class="svelte-oiduv9" data-svelte-h="svelte-18bnkmx">También puedes enviarme sugerencias o ideas para mejorar la plataforma.</p>`;
    }
  })}`;
});
export {
  Page as default
};
